/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.selat.esperpoc;

import br.com.selat.esperpoc.contract.TemperatureEvent;
import br.com.selat.esperpoc.service.EsperService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Date;
import java.util.Random;

public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    private static Random random = new Random();

    private static TemperatureEvent generateTemperatureRandom(){
        return new TemperatureEvent(random.nextInt(500), new Date());
    }

    public static void main(String[] args) {

        EsperService service = new EsperService();

        for(int i = 0; i < 100; i++){
            TemperatureEvent event = generateTemperatureRandom();
            service.handle(event);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                LOGGER.error("ERROR", e);
                Thread.currentThread().interrupt();
            }
        }


    }


}
